### ISSUE TITLE
[Rimworld 1.3/Ideology] Exception getting types in assembly D9Framework, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null

### ISSUE THREAD

**Issue by Remliel** [dninemfive/d9framework#7]
Exception getting types in assembly D9Framework, Version=1.0.0.0, Culture=neutral, PublicKeyToken=null
UnityEngine.StackTraceUtility:ExtractStackTrace ()
(wrapper dynamic-method) Verse.Log:Verse.Log.Error_Patch2 (string)
Verse.GenTypes/<get_AllTypes>d__4:MoveNext ()
System.Linq.Enumerable/WhereEnumerableIterator`1<System.Type>:ToList ()
System.Linq.Enumerable:ToList<System.Type> (System.Collections.Generic.IEnumerable`1<System.Type>)
Verse.GenTypes:AllSubclassesNonAbstract (System.Type)
RocketMan.Patches.RoomStatWorker_Patch/<TargetMethods>d__0:MoveNext ()
System.Collections.Generic.LargeArrayBuilder`1<System.Reflection.MethodBase>:AddRange (System.Collections.Generic.IEnumerable`1<System.Reflection.MethodBase>)
System.Collections.Generic.EnumerableHelpers:ToArray<System.Reflection.MethodBase> (System.Collections.Generic.IEnumerable`1<System.Reflection.MethodBase>)
System.Linq.Enumerable:ToArray<System.Reflection.MethodBase> (System.Collections.Generic.IEnumerable`1<System.Reflection.MethodBase>)
RocketMan.IPatchInfo`1<RocketMan.RocketPatch>:.ctor (System.Type)
RocketMan.RocketPatchInfo:.ctor (System.Type)
RocketMan.RocketPatcher:.cctor ()
(wrapper dynamic-method) System.Runtime.CompilerServices.RuntimeHelpers:System.Runtime.CompilerServices.RuntimeHelpers.RunClassConstructor_Patch1 (System.RuntimeTypeHandle)
(wrapper dynamic-method) Verse.StaticConstructorOnStartupUtility:Verse.StaticConstructorOnStartupUtility.CallAll_Patch3 ()
Verse.PlayDataLoader/<>c:<DoPlayLoad>b__4_3 ()
(wrapper dynamic-method) Verse.LongEventHandler:Verse.LongEventHandler.ExecuteToExecuteWhenFinished_Patch0 ()
Verse.LongEventHandler:UpdateCurrentAsynchronousEvent ()
Verse.LongEventHandler:LongEventsUpdate (bool&)
(wrapper dynamic-method) Verse.Root:Verse.Root.Update_Patch1 (Verse.Root)
(wrapper dynamic-method) Verse.Root_Entry:Verse.Root_Entry.Update_Patch0 (Verse.Root_Entry)

https://gist.github.com/a82c4ea18f72e64d1af3c7a9130a156f

**Comment by dninemfive** [comment]
Uh, yeah, I haven't finished updating to 1.3 yet, so I'm not surprised it's having issues.

**Comment by Remliel** [comment]
Sure, it's having issues. Just wanted to toss this your way in case you needed some additional input on what needs updating. Good luck!
